# Generated by Django 6.1 on 2026-10-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendind', 'Pending'), ('Delivered', 'delivered'), ('Cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
