# Generated by Django 6.1 on 2026-09-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
